### PR TITLE
Add node resolution; fix isImportOf

### LINKED ISSUE #32: Node modules are not resolved by the compiler.
Grimlock does not resolve node module imports in the source files.

Why this is important: The below example currently works fine if FooElement were in the source file. If FooElement is in a node module, the TS compiler can't find it. The TS compiler needs to see that file to analyze the `@property` declaration, for example.

"foo" node module
```ts
export class FooElement extends LitElement {
  @property() bar: string;
}
```

source file
```
import {FooElement} from 'foo';
/**
 * @soyCompatible
 */
export class MyElement extends FooElement {

  render() {
    return html`<h1>Hello ${this.bar}</h1>`;
  }
}
```

Suggestion:
We most likely need to add node resolution to the file system overlay in OverlayLanguageServiceHost

### LINKED ISSUE #33: SourceFileConverter.isImportOf does not work for re-exported members
### Context:

This method is called like so:

`this.isImportOf(node, 'property', 'lit-element/lib/decorators.js')`

and the docstring reads 

"Returns true if node is an identifier that references the import named name from a module with specifier specifier."

### Issue:

This method fails if the identifier is re-exported. For example the method would *incorrectly* return false in the above example if 'property' were imported from 'foo/bar', which in turn imported 'property' from 'lit-element/lib/decorators.js'.

### PR DESCRIPTION
**Pull request by straversi**
There are two related pieces of work in this PR, separated by commit:

#### What
Enable Grimlock to resolve node modules when compiling the source file.

#### Why
The type checker sometimes needs type information that resides within dependencies. For example, a soyCompatible custom element may extend an imported class that contains an @property that is consumed by the custom element. See #32 for a more detailed example.

Fixes #32 

#### What
Replace usages of `isImportOf` with `isDeclaredIn`, a new method that can determine if a given identifier's symbol is declared in the given file.

#### Why
`isImportOf` checks if the given identifier's local declaration is imported from the given source. E.g., answering the question "is `html` imported from `lit-element`"? The problem occurs when `html` is imported via a proxy module, i.e. `html` is imported from `foo` which re-exports `html` from `lit-element`. What we really want to know is if `html` was originally declared in `lit-element`.

`isDeclaredIn` does this. It finds the original declaration and compares the source file against the given file name.

`isDeclaredIn` uses `ts.TypeChecker.getAliasedSymbol`. This method requires that the original declaration's *source* be loaded. Hence, adding node resolution and allowing JS sources to be loaded was required. This work is done by the first commit in this PR.

Fixes #33

### CODE REVIEW

**Comment by straversi** [comment]
Note: `isImportOf` has no usages after this PR, it could be safely removed for now.

File: src/lib/overlay-language-service-host.ts [hunk 1]
```diff
@@ -81,6 +82,30 @@ export class OverlayLanguageServiceHost implements ts.LanguageServiceHost {
     return contents;
   }
 
+  resolveModuleNames(
+    moduleNames: string[],
+    containingFile: string
+  ): ts.ResolvedModule[] {
+    const resolvedModules: ts.ResolvedModule[] = [];
+    for (const moduleName of moduleNames) {
```
Comment (justinfagnani) [inline src/lib/overlay-language-service-host.ts]: nit: I'd use `moduleNames.map()` so it's clear that this is a 1-1 transform of all the elements.

File: src/lib/overlay-language-service-host.ts [hunk 2]
```diff
@@ -81,6 +82,30 @@ export class OverlayLanguageServiceHost implements ts.LanguageServiceHost {
...
+      let result = ts.resolveModuleName(moduleName, containingFile, this.compilerOptions, {
+        fileExists: this.fileExists.bind(this),
```
Comment (justinfagnani) [inline src/lib/overlay-language-service-host.ts]: Why don't you pass `this` as the host?

```ts
ts.resolveModuleName(moduleName, containingFile, this.compilerOptions, this);
```

File: src/lib/overlay-language-service-host.ts [hunk 3]
```diff
@@ -81,6 +82,30 @@ export class OverlayLanguageServiceHost implements ts.LanguageServiceHost {
...
+        readFile: this.readFile.bind(this),
+      });
+      if (result.resolvedModule) {
+        resolvedModules.push(result.resolvedModule);
+      } else {
+        // If default resolution doesn't work, try node resolution.
```
Comment (justinfagnani) [inline src/lib/overlay-language-service-host.ts]: When is this necessary? I'd be fine relying on TypeScript's default resolution, or figuring out why it's not working (I believe it does node resolution, at least with the right setting).

File: src/lib/source-file-converter.ts [hunk 4]
```diff
@@ -912,6 +913,45 @@ export class SourceFileConverter {
...
+   * Returns true if `node` is an identifier that is originally declared in
+   * a file called `fileName`.
+   *
+   * @param node The node to check. It can be any node type but this will return
+   *     false for non-Itentifiers.
+   * @param fileName Either a single filename, or an array of filenames. An
+   *     array is allowed because symbols may be declared in any of several file
+   *     types, for example: `.js`, `.ts`, or `.d.ts`.
+   */
+  isDeclaredIn(node: ts.Node, fileName: string | string[]) {
```
Comment (justinfagnani) [inline src/lib/source-file-converter.ts]: Is this check good enough? This just checks that the node is from this module, but we want to know that it's a particular export of the module. Instead, could we get `html` from `lit-html` and check that the nodes are equivalent?

File: src/lib/overlay-language-service-host.ts (hunk 3 above)
Comment (straversi) [reply src/lib/overlay-language-service-host.ts]: giphy (1)

Comment (straversi) [reply src/lib/overlay-language-service-host.ts]: ...thanks haha. I'll remove it and flip the `moduleResolution` compiler option to 'Node' 🤣

File: src/lib/overlay-language-service-host.ts (hunk 2 above)
Comment (straversi) [reply src/lib/overlay-language-service-host.ts]: That would make too much sense

File: src/lib/source-file-converter.ts (hunk 4 above)
Comment (straversi) [reply src/lib/source-file-converter.ts]: Talked IRL. In 19a0fde, I resolve 'lit-html' and 'lit-element' once at the beginning of conversion and find symbols like `html` and `property`. During conversion, we can compare strict equality against these symbols. 👍

File: src/lib/source-file-converter.ts [hunk 5]
```diff
@@ -132,6 +140,49 @@ export class SourceFileConverter {
 
     const arraySymbol = symbols.filter((s) => s.name === 'Array')[0];
     this._arrayMapSymbol = arraySymbol.members!.get('map' as any)!;
+
+    // Get original html, property, and customElement symbols.
+    this.htmlSymbol = this.getExportOfModule('lit-html', 'html');
+    this.propertySymbol = this.getExportOfModule('lit-element/lib/decorators', 'property');
```
Comment (justinfagnani) [inline src/lib/source-file-converter.ts]: for my information: do these have to reference the original module, or would it work to do: `this.getExportOfModule('lit-element', 'property')`?

File: src/lib/source-file-converter.ts [hunk 6]
```diff
@@ -132,6 +140,49 @@ export class SourceFileConverter {
...
+  getExportOfModule(moduleName: string, symbolName: string): ts.Symbol | undefined {
+    const moduleInfo = ts.resolveModuleName(
+      moduleName,
+      this.sourceFile.fileName,
+      this.languageServiceHost.getCompilationSettings(),
+      this.languageServiceHost as ts.ModuleResolutionHost
+    ).resolvedModule;
+
+    if (moduleInfo === undefined) {
+      // TypeScript couldn't resolve moduleName.
```
Comment (justinfagnani) [inline src/lib/source-file-converter.ts]: Let's report, here. Above for the lit-* related symbols lets check and report again and ask "are you're importing lit-html or something imports it?" in the message.

File: src/lib/source-file-converter.ts [hunk 7]
```diff
@@ -132,6 +140,49 @@ export class SourceFileConverter {
...
+      return;
+    }
+
+    const moduleEntryFileName = moduleInfo.resolvedFileName;
+    const moduleFile = this.program.getSourceFiles().find((sf) => sf.fileName === moduleEntryFileName)!;
+
+    if (moduleFile === undefined) {
+      // moduleName is not included by the program's source.
```
Comment (justinfagnani) [inline src/lib/source-file-converter.ts]: report here too

File: src/lib/source-file-converter.ts [hunk 8]
```diff
@@ -834,14 +885,41 @@ export class SourceFileConverter {
...
   }
 
+  /**
+   * Follow all aliases, such as imports, for the given node. Return the original
+   * symbol. If node is not an identifier, this method will return `undefined`.
+   *
+   * @param node The node to check. It can be any node type but this will return
+   *     undefined for non-Itentifiers.
+   */
+  getOriginalSymbol(node: ts.Node): ts.Symbol | undefined {
```
Comment (justinfagnani) [inline src/lib/source-file-converter.ts]: Do we call this in any place where `undefined` is an acceptable return value? Should we throw/report instead?

File: src/test/lit-element_test.ts [hunk 9]
```diff
@@ -374,4 +374,165 @@ describe('grimlock', () => {
       );
     });
   });
+
+  it('converts mwc-checkbox', () => {
```
Comment (justinfagnani) [inline src/test/lit-element_test.ts]: is this working?

File: src/lib/source-file-converter.ts (hunk 5 above)
Comment (straversi) [reply src/lib/source-file-converter.ts]: It had to be the original module. BUT. You inspired me to look into why.

I discovered that `<module symbol>.exports` returns only exports that originate from the module in question, while `checker.getExportsOfModule(<module symbol>)` returns all exports _including_ re-exported declarations. 🙃

Comment (straversi) [reply src/lib/source-file-converter.ts]: I'm gonna use the latter approach so we can do `this.getExportOfModule('lit-element', 'property')`, which looks nice

File: src/lib/source-file-converter.ts (hunk 6 above)
Comment (straversi) [reply src/lib/source-file-converter.ts]: To continue our IRL chat -- I've been playing around with this. If a user only imports lit-html, they'll always get diagnostics a la "couldn't find lit-element", which would be confusing. We _also_ can't insert an ErrorExpression command at this point, since we don't have the concept of 'commands' until `convertFile`. 

Idea: what if we allow the lit-* related symbols to be undefined. Then later during `convertFile`, if we ever compare against an undefined lit-* symbol, we add diagnostics AND and ErrorExpression.

This would work well for users not importing lit-element: because `convertFile` would never run a code path that compares against the `property` symbol.

Thoughts?

File: src/test/lit-element_test.ts (hunk 9 above)
Comment (straversi) [reply src/test/lit-element_test.ts]: Nope, we're missing the boilerplate and property types. I've opened an issue for property types, PR incoming.

I can make this spec an `xit` so it doesn't run for now.

File: src/lib/source-file-converter.ts (hunk 6 above)
Comment (straversi) [reply src/lib/source-file-converter.ts]: Ooh. Since we can generate AST error expressions once we start `convertFile`, perhaps the best thing to do would be to return an error expression in convertFile:

https://github.com/PolymerLabs/grimlock/blob/899c5da30443ed783a9c6c11b5bbddcbdf14ffb8/src/lib/source-file-converter.ts#L137-L150

If we find a soy compatible template function declaration and we can't resolve 'lit-html', then return an error expression. If we find a soy compatible class declaration and we can't resolve 'lit-element', return an error expression and report diagnostics.
